### PR TITLE
fix: Fix comment generation

### LINKED ISSUE #36: Examples generated incorrectly (`@example [object Object]`)
It looks like object examples get stringified incorrectly.

screenshot-20220222T200832-S6SdWKun

### LINKED ISSUE #57: Syntax error generating types when example includes `*/`
Hi, I've discovered a syntax error when attempting to generate types for an openapi spec containing "*/" in one of my examples.

The `openapi.json` contains a `components.schema` declaration (roughly) as follows:
```
      "CronTimingCreate": {
        "title": "CronTimingCreate",
        "required": [
          "type",
          "cron_expression"
        ],
        "type": "object",
        "properties": {
          "cron_expression": {
            "title": "Cron Expression",
            "type": "string",
            "description": "The string representing the timing's cron expression.",
            "format": "cron-string",
            "example": "*/5 * * * *"
          },
        },
        "additionalProperties": false,
        "description": "Cron timing schema for create requests."
      }
```

The issue seems to be stemming from the `example`, which contains `*/` -- which I believe is being detected as the end of the comment here: https://github.com/fabien0102/openapi-codegen/blob/2105e99f03fe71251cf347e905c88cae9b4a39a1/plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts#L614-L615

Ultimately, I get this output from `npx openapi-codegen gen api`:
```
Syntax Error: Unexpected token (468:8)
  466 |      * @format cron-string
  467 |      * @example 5 * * * *
> 468 |      */*/
      |        ^
  469 |     cron_expression: string;
  470 |     /*
  471 |      * The IANA time zone to use convert `time` in this timing.
  466 |      * @format cron-string
  467 |      * @example 5 * * * *
> 468 |      */*/
      |        ^
  469 |     cron_expression: string;
  470 |     /*
  471 |      * The IANA time zone to use convert `time` in this timing.
```

### PR DESCRIPTION
**Pull request by fabien0102**
Specs containing `*/` are producting non valid code.

Closed #57 
Closed #36

### CODE REVIEW

File: plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts [hunk 1]
```diff
@@ -544,6 +544,27 @@ const getJSDocComment = (
...
+      !JSON.stringify(value).includes(multilineEndChar)
+    ) {
+      return f.createIdentifier(JSON.stringify(value));
+    }
+
+    if (typeof value === "boolean" || typeof value === "number") {
+      return f.createIdentifier(value.toString());
+    }
+
+    return f.createIdentifier("[see original specs]");
```
Comment (atrakh) [inline plugins/typescript/src/core/schemaToTypeAliasDeclaration.ts:565]: What do you think of adding a comment like this for folks that may see this placeholder in the future?
```suggestion
    // Value is not stringifiable
    // See https://github.com/fabien0102/openapi-codegen/issues/36, https://github.com/fabien0102/openapi-codegen/issues/57
    return f.createIdentifier("[see original specs]");
```
